---
title: "Case Study 2"
author: "J. Kyle Wathen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Case Study 2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Case Study 2
This case study covers a simple case with one ISA and no interim analysis (IA) to help the user become famaliar with the software and the necessay elemnts to setup the simulation.  This packge is designed with the intentent that others can add new fuctionality as needed through the use of S3 classes.  In this case study, we add a new analysis model that is not currently part of the package.   As the R comunity for this package grows, others may add functionitly, like the new analysis model in this case study, to the base package.  

The R code may be found in the Examples/CaseStudy2

## Assumptions 

* Platform trial with 1 ISA
* No Interim analysis
* Final Analysis (FA) when all patients have the outcome observed.
* 30 patients on control (C) 60 patients on treatment (T)
* Primary outcome is repeated measure evaluated at baseline, 4, 8, 12, 16, 20 and 24 weeks after treatment
* Analyze difference from baseline to week 24 compared to control
* Minimum Acceptable Value MAV = 0.5 difference between control and treatment
    + This is the minimum difference between treatment and control 
    $$ ( \mu_{24} - \mu_0 )_{C} – (\mu_{24} - m_0 )_{T}$$

### R Code
Begin with the BuildMe.R file.    This file loads the PlatformTrialSimulator package and sources the design file.  
The file TrialDesign.R contains the function necessary to set-up the design object.
The file SimulationDesign.R contains the functions necessary to set-up the simulation design. 
